import { NgModule }      from '@angular/core';
import {MdSidenavModule,
        MdTableModule,
        MdInputModule,
        MdButtonModule,
        MdSelectModule,
        MdIconModule,
        MdToolbarModule,
        MdMenuModule,
        MdCardModule,
        MdCheckboxModule,
        MdListModule,
        MdDialogModule,
        MdRadioModule,
        MdAutocompleteModule,
        MdPaginatorModule,
        MdProgressSpinnerModule,
        MdDatepickerModule,
        MdExpansionModule,

} from '@angular/material';
@NgModule({
    imports:[
        MdSidenavModule,
        MdTableModule,
        MdInputModule,
        MdButtonModule,
        MdSelectModule,
        MdIconModule,
        MdToolbarModule,
        MdMenuModule,
        MdCardModule,
        MdCheckboxModule,
        MdSidenavModule,
        MdListModule,
        MdDialogModule,
        MdRadioModule,
        MdAutocompleteModule,
        MdPaginatorModule,
        MdProgressSpinnerModule,
        MdDatepickerModule,
        MdExpansionModule,
    ],
    exports:[
        MdSidenavModule,
        MdTableModule,
        MdInputModule,
        MdButtonModule,
        MdSelectModule,
        MdIconModule,
        MdToolbarModule,
        MdMenuModule,
        MdCardModule,
        MdCheckboxModule,
        MdListModule,
        MdDialogModule,
        MdRadioModule,
        MdAutocompleteModule,
        MdPaginatorModule,
        MdProgressSpinnerModule,
        MdDatepickerModule,
        MdExpansionModule,

    ],
})
export class SharedModule { }
